

version: '3'

services:
  api:
    build: api
    command: ["python3", "app.py"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    expose:
      - "5001"
    ports:
      - "5001:5001"

  client:
    build: ui
    command: ["npm", "start"]
    volumes:
      - ./ui:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules: